services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NormanSeibert\Ldap\:
    resource: '../Classes/*'

  NormanSeibert\Ldap\Command\ImportUsersCommand:
    tags:
      - name: 'console.command'
        command: 'ldap:importUsers'